from unittest.mock import Mock

import pytest

from chuva_vazao_utils.exception_handler.exception_handler import exception_handler


class ExceptionHandlerTest(Exception):
    pass


def test_handler_exception_with_exception():
    handler_exception_mock = Mock()

    @exception_handler(handler_exception_mock, 'nome_processo')
    def print_exception():
        raise ExceptionHandlerTest('test exception')

    with pytest.raises(ExceptionHandlerTest):
        print_exception()

    handler_exception_mock.assert_called_once_with('Erro ao executar processo nome_processo:\ntest exception')


def test_handler_exception_with_no_exception():
    handler_exception_mock = Mock()

    @exception_handler(handler_exception_mock)
    def print_exception():
        pass

    print_exception()

    handler_exception_mock.assert_not_called()


def test_handler_exception_with_no_exception_and_has_return():
    handler_exception_mock = Mock()

    @exception_handler(handler_exception_mock)
    def print_exception():
        return 'test'

    response = print_exception()

    handler_exception_mock.assert_not_called()
    assert response == 'test'
